name: Release

on:
  push:
    branches: [main]

permissions:
  contents: write
  pull-requests: write
  id-token: write

jobs:
  release:
    uses: nightwatch-astro/.github/.github/workflows/rust-release.yml@278fc3e6e2ab154e146c07107c95d192919bf84b # main
    secrets: inherit
